1. Get the Customer Information By Id (GET Mapping)
http://localhost:8080//online-auction-system/customers/get/id

2. Get all the customers (GET Mapping)
http://localhost:8080//online-auction-system/customers/get/all

3. Delete the Customer by Id (Delete Mapping)
http://localhost:8080//online-auction-system/customers/delete/id

4. Register the customer (POST Mapping)

   http://localhost:8080//online-auction-system/customers/register
   
   Request body:
   {  
    "username": "Adamya",
    "password": "password@123",
    "fatherName": "Raman Singh",
    "email": "adamya@gmail.com",
    "phoneNumber": 9999000088,
    "address": "adamya@yahoo.com"
   }
   
5. Update the Existing customer (PUT Mapping)
   http://localhost:8080//online-auction-system/customers/update
   
   {
    "id": 1,
    "username": "Adamya",
    "password": "password123",
    "email": "adamya@gmail.com",
    "phoneNumber": 9999000088,
    "address": "adamya@yahoo.com"
   }
